import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">{children}</body>
    </html>
  );
}
import Link from 'next/link';
import { Activity, Trophy, Newspaper, Sparkles } from 'lucide-react';

export default function Navbar() {
  return (
    <nav className="bg-slate-900/90 backdrop-blur border-b border-slate-800 sticky top-0 z-50 px-6 py-3.5" dir="rtl">
      <div className="max-w-6xl mx-auto flex items-center justify-between">
        
        {/* شعار المنصة */}
        <Link href="/" className="flex items-center gap-2">
          <span className="text-xl font-black text-emerald-400 tracking-wider">EDGE</span>
          <span className="text-xl font-bold text-white">FOOTBALL</span>
        </Link>

        {/* الروابط الأساسية */}
        <div className="flex items-center gap-6 text-sm font-medium">
          <Link href="/live" className="flex items-center gap-1.5 text-slate-300 hover:text-red-400 transition">
            <Activity className="w-4 h-4 text-red-500" />
            المباريات المباشرة
          </Link>
          <Link href="/standings" className="flex items-center gap-1.5 text-slate-300 hover:text-emerald-400 transition">
            <Trophy className="w-4 h-4 text-amber-400" />
            ترتيب الدوريات
          </Link>
          <Link href="/" className="flex items-center gap-1.5 text-slate-300 hover:text-emerald-400 transition">
            <Sparkles className="w-4 h-4 text-emerald-400" />
            محرك الصياغة
          </Link>
        </div>

      </div>
    </nav>
  );
}